### ISSUE TITLE
Improve productivity

### ISSUE THREAD

**Issue by chibenwa** [linagora/tmail-flutter#1084]
- [x] Drag n drop to move emails

 - [ ] Drag and drop attachments

 - [x] next / previous messages

 - [x] Open an email in another tab

....

**Comment by chibenwa** [comment]
Issue for drag n drop attachmenthttps://github.com/linagora/tmail-flutter/issues/307

Redoundant. Closing.
