### ISSUE TITLE
[EPIC][Mail] Multiple accounts

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#2339]

**Comment by hoangdat** [comment]
### Notification 
- [ ] How not active account receive notification in Android?
- [ ] How not active account receive notification in iOS?
- [ ] - [ ] How not active account receive details notification in iOS? (NSE)
