### ISSUE TITLE
[EPIC] SaaS integration

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#845]
### Basic functions for SaaS:
- [ ] Sign up
- [ ] Login with OIDC
- [ ] (Still support self-host app in both cases: BasicAuth - OIDC)
- ...

### Functions to leverage LINAGORA ecosystem: 
- [ ] Applications discovery

1. With LinShare: 
- [ ] Browse attachment: Raw file/ LinShare file (link?)
- [ ] Backup mailbox
- [ ] Backup emails
- [ ] Auto backups (daily/weekly/...)
- [ ] ...
2. With Twake:
- [ ] Auto complete with contact from Twake
- [ ] ...

Hi @chibenwa, I brainstormed some ideas related to SaaS. Don't hesitate to update it. And please update the requirements for SaaS in this epic. Thanks and BRs

**Comment by poupotte** [comment]
@chibenwa, @hoangdat  : In my point of view, this issue should be considered okay, right?

**Comment by chibenwa** [comment]
Yes let's close this legacy issue
