### ISSUE TITLE
Base on `accountCapabilities` to set up Tmail functions

### ISSUE THREAD

**Issue by hoangdat** [linagora/tmail-flutter#939]
### Desc:
- in Session of Fastmail, `capabilities` does not have details object. Fx: `urn:ietf:params:jmap:mail`. So it makes our deserialize `Session` failed.
- some functions we base on the `capabilities`, we should check the capabilities from `accountCapabilities` instead
  - [x] delete multiple mailboxes (#943)
  - [x] binding or not `auto complete` module (#944)
  - [x] binding `vacation` function (#944)
  - [x] binding `identity` function -> no need, because `identity` not have separate capability
  - [x] binding `rules` (#952)
  - [x] binding `forwarding` (#952)
  - [x] maxFileSize, max.... for upload/download (#952)
